import type { CharacterState, CharacterStatePreset } from "../types/character";

export const CHARACTER_STATE_PRESETS: Readonly<Record<CharacterState, CharacterStatePreset>> = {
  idle: {
    state: "idle",
    label: "待機中",
    shortLabel: "待機",
    message: "自然な呼吸で待っています",
    tone: "blue",
    expressions: [{ name: "neutral", weight: 1 }],
    posture: { headPitch: 0, headYaw: 0, headRoll: 0, neckPitch: 0, chestPitch: 0, chestRoll: 0 },
    gaze: { mode: "pointer", pointerInfluence: 0.32, offsetX: 0, offsetY: 0 },
    motion: { speed: 1, breath: 1, sway: 1, bounce: 0, blink: 1 },
  },
  listening: {
    state: "listening",
    label: "聞いています",
    shortLabel: "聞く",
    message: "あなたの話に注意を向けています",
    tone: "teal",
    expressions: [
      { name: "relaxed", weight: 0.25 },
      { name: "neutral", weight: 1 },
    ],
    posture: { headPitch: 0.035, headYaw: 0, headRoll: 0, neckPitch: 0.025, chestPitch: 0.035, chestRoll: 0 },
    gaze: { mode: "pointer", pointerInfluence: 0.42, offsetX: 0, offsetY: 0 },
    motion: { speed: 0.8, breath: 0.72, sway: 0.45, bounce: 0, blink: 0.9 },
  },
  thinking: {
    state: "thinking",
    label: "考えています",
    shortLabel: "考える",
    message: "少し視線を外して整理しています",
    tone: "violet",
    expressions: [
      { name: "neutral", weight: 1 },
      { name: "relaxed", weight: 0.15 },
    ],
    posture: { headPitch: -0.025, headYaw: -0.07, headRoll: 0.07, neckPitch: 0, chestPitch: 0, chestRoll: 0.018 },
    gaze: { mode: "away", pointerInfluence: 0.08, offsetX: -0.24, offsetY: 0.14 },
    motion: { speed: 0.62, breath: 0.7, sway: 0.35, bounce: 0, blink: 0.82 },
  },
  explaining: {
    state: "explaining",
    label: "説明しています",
    shortLabel: "説明",
    message: "正面を見て分かりやすく伝えます",
    tone: "blue",
    expressions: [
      { name: "relaxed", weight: 0.18 },
      { name: "neutral", weight: 1 },
    ],
    posture: { headPitch: 0, headYaw: 0, headRoll: 0, neckPitch: 0, chestPitch: -0.012, chestRoll: 0 },
    gaze: { mode: "center", pointerInfluence: 0.12, offsetX: 0, offsetY: 0 },
    motion: { speed: 1.08, breath: 0.85, sway: 0.7, bounce: 0.08, blink: 0.92 },
  },
  happy: {
    state: "happy",
    label: "うれしい",
    shortLabel: "笑顔",
    message: "明るい表情で応答します",
    tone: "rose",
    expressions: [
      { name: "happy", weight: 0.85 },
      { name: "relaxed", weight: 0.5 },
      { name: "neutral", weight: 1 },
    ],
    posture: { headPitch: -0.02, headYaw: 0, headRoll: -0.025, neckPitch: -0.01, chestPitch: -0.025, chestRoll: 0 },
    gaze: { mode: "pointer", pointerInfluence: 0.3, offsetX: 0, offsetY: 0.02 },
    motion: { speed: 1.22, breath: 1.08, sway: 1.08, bounce: 0.35, blink: 1.08 },
  },
  gentle: {
    state: "gentle",
    label: "やさしく応答",
    shortLabel: "やさしく",
    message: "穏やかな表情と動きに切り替えます",
    tone: "teal",
    expressions: [
      { name: "relaxed", weight: 0.55 },
      { name: "happy", weight: 0.22 },
      { name: "neutral", weight: 1 },
    ],
    posture: { headPitch: 0.02, headYaw: 0, headRoll: 0.02, neckPitch: 0.01, chestPitch: 0.01, chestRoll: 0 },
    gaze: { mode: "center", pointerInfluence: 0.16, offsetX: 0, offsetY: -0.015 },
    motion: { speed: 0.62, breath: 0.72, sway: 0.38, bounce: 0, blink: 0.86 },
  },
  curious: {
    state: "curious",
    label: "興味を示す",
    shortLabel: "興味",
    message: "少し首をかしげて注目しています",
    tone: "violet",
    expressions: [
      { name: "surprised", weight: 0.24 },
      { name: "neutral", weight: 1 },
    ],
    posture: { headPitch: -0.015, headYaw: 0.04, headRoll: -0.12, neckPitch: 0, chestPitch: 0.012, chestRoll: -0.025 },
    gaze: { mode: "pointer", pointerInfluence: 0.46, offsetX: 0.05, offsetY: 0.04 },
    motion: { speed: 0.92, breath: 0.82, sway: 0.62, bounce: 0.05, blink: 0.94 },
  },
  cautious: {
    state: "cautious",
    label: "慎重に確認",
    shortLabel: "慎重",
    message: "断定せず、落ち着いて確認します",
    tone: "amber",
    expressions: [
      { name: "sad", weight: 0.16 },
      { name: "neutral", weight: 1 },
    ],
    posture: { headPitch: 0.035, headYaw: 0, headRoll: 0.018, neckPitch: 0.012, chestPitch: 0.025, chestRoll: 0 },
    gaze: { mode: "center", pointerInfluence: 0.1, offsetX: 0, offsetY: -0.025 },
    motion: { speed: 0.52, breath: 0.58, sway: 0.25, bounce: 0, blink: 0.78 },
  },
  confused: {
    state: "confused",
    label: "聞き返します",
    shortLabel: "困惑",
    message: "意味を確認するため、聞き返す姿勢です",
    tone: "amber",
    expressions: [
      { name: "sad", weight: 0.28 },
      { name: "surprised", weight: 0.18 },
      { name: "neutral", weight: 1 },
    ],
    posture: { headPitch: 0.03, headYaw: -0.025, headRoll: 0.13, neckPitch: 0.018, chestPitch: 0.02, chestRoll: 0.03 },
    gaze: { mode: "pointer", pointerInfluence: 0.35, offsetX: -0.05, offsetY: 0 },
    motion: { speed: 0.68, breath: 0.66, sway: 0.42, bounce: 0, blink: 1.04 },
  },
  error: {
    state: "error",
    label: "確認が必要です",
    shortLabel: "エラー",
    message: "処理を続けられないため、操作を確認してください",
    tone: "rose",
    expressions: [
      { name: "sad", weight: 0.42 },
      { name: "neutral", weight: 1 },
    ],
    posture: { headPitch: 0.055, headYaw: 0, headRoll: -0.025, neckPitch: 0.025, chestPitch: 0.035, chestRoll: 0 },
    gaze: { mode: "center", pointerInfluence: 0, offsetX: 0, offsetY: -0.06 },
    motion: { speed: 0.42, breath: 0.5, sway: 0.18, bounce: 0, blink: 0.68 },
  },
};

export function getCharacterStatePreset(state: CharacterState): CharacterStatePreset {
  return CHARACTER_STATE_PRESETS[state];
}
